### ISSUE TITLE
TSSV fails with verbose output

### ISSUE THREAD

**Issue by agynna** [Jerrythafast/FDSTools#1]
When running TSSV with verbose output (--dir option), it performs the task but fails upon closing the verbose output files. Commenting out line 635 in tssv.py gets rid of the error. 

Example command: 
`fdstools tssv --dir results/example-2800M/ --indel-score 2 --mismatches 0.1 --num-threads 2 data/library.txt data/input.fastq > /dev/null`

Terminal output: 
```
marker  unique_seqs     tPaired fPaired rPaired tLeft   fLeft   rLeft   tRight  fRight  rRight                          
[7 lines retracted]

total reads     554718                                                                                                  
unrecognised reads      25306                                                                                           
usage: fdstools tssv [-h] [-v] [-d] [-F FORMAT] [-R FILE] [-L N] [-D DIR]                                                                    
					 [-T THREADS] [-X] [-m MISMATCHES] [-n N] [-a N] [-B]                                                                    
					 [-M ACTION]                                                                                                             
					 LIBRARY [IN] [OUT]                                                                                 
fdstools tssv: error: too many values to unpack (expected 2)
```

All output files are created and have the expected content. 

Cheers, 
Arvid

**Comment by Jerrythafast** [comment]
Thanks for reporting this Arvid! (And yay, first issue on Github :) )
I have pushed a fix to `master`, which will make its way into the next release soon.

**Comment by agynna** [comment]
An exemplary quick bugfix! I can confirm it works now.

**Comment by Jerrythafast** [comment]
Excellent! Thanks again :)
