### ISSUE TITLE
[Py3.12] FDSTools failed to load

### ISSUE THREAD

**Issue by waweey** [Jerrythafast/FDSTools#2]
Hi, 

I have encountered this issue: 

FDSTools failed to load 'allelefinder': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'bganalyse': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'bgcorrect': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'bgestimate': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'bghomraw': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'bghomstats': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'bgmerge': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'bgpredict': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'findnewalleles': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'libconvert': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'library': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'pipeline': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'samplestats': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'seqconvert': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'stuttermark': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'stuttermodel': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'tssv': 'FileFinder' object has no attribute 'find_module'
FDSTools failed to load 'vis': 'FileFinder' object has no attribute 'find_module'

Can you please suggest a solution? I have tried reinstalling FDStools and installing it again but the same issue exists. I am running the most updated version of python

**Comment by Jerrythafast** [comment]
Hi @waweey,

FDSTools currently **does not support** Python 3.12. We have a fix for this in the next release, which should come later this month, but for now my advise is to downgrade to Python 3.11 to avoid this issue.

I'm sorry for the inconvenience!

Jerry

**Comment by waweey** [comment]
Thank you, Jerry, for the prompt response

**Comment by waweey** [comment]
Hi again jerry, I have followed all the steps provided for the ISFG exercise 1.  

For the (fdstools tssv --num-threads 8 --report tssv1-report.txt ForenSeqA ForenseqARef_R1.fasta.gz tssv1-output.txt) regards of the number of threads, the following error is observed:

**fdstools : usage: fdstools tssv [-h] [-v] [-d] [-F FORMAT] [-R FILE] [-L N] [-D DIR]
At line:1 char:1
+ fdstools tssv --num-threads 8 --report tssv1-report.txt ForenSeqA For ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (usage: fdstools...[-L N] [-D DIR]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
                     [-T THREADS] [-X] [-m MISMATCHES] [-n N] [-a N] [-B]
                     [-M ACTION]
                     LIBRARY [IN] [OUT]
fdstools tssv: error: argument LIBRARY: Sequence for chr13:20327551..20327614 is unavailable and could not be downloaded automatically. Please run 'strnaming refseq-cache chr13:20327551..20327614' on a system with internet 
access and manually transfer the downloaded files to 'C:\Users\q8dj\.strnaming-cache'.**


I have a PC with internet connection and I have tried to cash the chr13 manually but still the error is still showing.

**strnaming : usage: strnaming [-h] [-v] [-d] ACTION ...
At line:1 char:1
+ strnaming refseq-cache chr13:20327551..20327614
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (usage: strnamin...[-d] ACTION ...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
strnaming: error: Sequence for chr13:20327551..20327614 is unavailable and could not be downloaded automatically. Please run 'strnaming refseq-cache chr13:20327551..20327614' on a system with internet access and manually 
transfer the downloaded files to 'C:\Users\q8dj\.strnaming-cache'.
Something went wrong while trying to cache refseq range chr13:20327551..20327614**

**Comment by Jerrythafast** [comment]
Hi @waweey,

Looks like for some reason FDSTools/STRNaming is unable to contact the Ensembl REST API. It should download the reference sequence by contacting http://rest.ensembl.org/sequence/region/human/chr13:20324353..20336640?content-type=text/plain 

Could you try if that link works (in a web browser or using a command-line utility such as cURL/wget) on that PC?

If it does, I'm curious if we can get more information by adding `--debug` to the command like this:
```
strnaming refseq-cache --debug chr13:20327551..20327614
```

**Comment by waweey** [comment]
Hi Jerry, 

### The link works hopefully but still getting the error message:

PS C:\Users\q8dj> strnaming refseq-cache --debug chr13:20327551..20327614

**strnaming : usage: strnaming [-h] [-v] [-d] ACTION ...
At line:1 char:1
+ strnaming refseq-cache --debug chr13:20327551..20327614
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (usage: strnamin...[-d] ACTION ...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
strnaming: error: The following arguments are not known. Please check spelling and argument order: '--debug'.**

### Another input: 
PS C:\Users\q8dj> strnaming --debug refseq-cache chr13:20327551..20327614
strnaming : Traceback (most recent call last):
At line:1 char:1
+ strnaming --debug refseq-cache chr13:20327551..20327614
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\site-packages\strnaming\refseq_cache.py", line 147, in _get_chunk
    with gzip.open(chunkfilepath, "rt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\q8dj\\.strnaming-cache\\refseq-13-1654.txt.gz'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\site-packages\strnaming\refseq_cache.py", line 91, in acquire
    self.lock = LOCK_FILE.open("x")
                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileExistsError: [Errno 17] File exists: 'C:\\Users\\q8dj\\.strnaming-cache\\cache.lock'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\site-packages\strnaming\refseq_cache.py", line 155, in _get_chunk
    with LockFile():
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\site-packages\strnaming\refseq_cache.py", line 82, in __enter__
    self.acquire()
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\site-packages\strnaming\refseq_cache.py", line 95, in acquire
    raise ValueError(
ValueError: Failed to acquire lock within 60 seconds; please remove lock file manually if this problem persists (C:\Users\q8dj\.strnaming-cache\cache.lock)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Scripts\strnaming.exe\__main__.py", line 7, in <module>
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\site-packages\strnaming\strnaming.py", line 162, in main
    cProfile.runctx("args.func(args)", globals(), locals(), sort="tottime")
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\cProfile.py", line 20, in runctx
    return _pyprofile._Utils(Profile).runctx(statement, globals, locals,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\profile.py", line 63, in runctx
    prof.runctx(statement, globals, locals)
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\cProfile.py", line 101, in runctx
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\site-packages\strnaming\strnaming.py", line 88, in run_refseq_cache
    refseq_cache.get_refseq(rng.group(1), int(rng.group(2)), int(rng.group(3)))
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\site-packages\strnaming\refseq_cache.py", line 204, in get_refseq
    seq += _get_chunk(chromosome, chunk, skip, length)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\q8dj\AppData\Local\Programs\Python\Python311\Lib\site-packages\strnaming\refseq_cache.py", line 177, in _get_chunk
    raise ValueError(
ValueError: Sequence for chr13:20327551..20327614 is unavailable and could not be downloaded automatically. Please run 'strnaming refseq-cache chr13:20327551..20327614' on a system with internet access and manually transfer the downloaded files to 'C:\Users\q8dj\.strnaming-cache'.
Something went wrong while trying to cache refseq range chr13:20327551..20327614
         2600 function calls (2560 primitive calls) in 60.118 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      240   60.087    0.250   60.087    0.250 {built-in method time.sleep}
      243    0.023    0.000    0.024    0.000 {built-in method io.open}
        1    0.004    0.004   60.117   60.117 refseq_cache.py:87(acquire)
      241    0.001    0.000    0.026    0.000 pathlib.py:1036(open)
      243    0.001    0.000    0.001    0.000 pathlib.py:546(__fspath__)
      247    0.000    0.000    0.000    0.000 pathlib.py:536(__str__)
      242    0.000    0.000    0.000    0.000 {built-in method time.time}
      241    0.000    0.000    0.000    0.000 {built-in method io.text_encoding}
      7/1    0.000    0.000    0.000    0.000 _parser.py:509(_parse)
     10/1    0.000    0.000    0.000    0.000 _compiler.py:37(_compile)
      5/1    0.000    0.000    0.000    0.000 _parser.py:449(_parse_sub)
        1    0.000    0.000   60.118   60.118 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {built-in method nt.stat}
        8    0.000    0.000    0.000    0.000 _compiler.py:241(_optimize_charset)
        1    0.000    0.000    0.000    0.000 {built-in method nt.mkdir}
        1    0.000    0.000    0.000    0.000 _compiler.py:571(_code)
     13/4    0.000    0.000    0.000    0.000 _parser.py:174(getwidth)
        1    0.000    0.000   60.117   60.117 refseq_cache.py:134(_get_chunk)
       57    0.000    0.000    0.000    0.000 _parser.py:164(__getitem__)
       53    0.000    0.000    0.000    0.000 _parser.py:233(__next)
      169    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}
  135/123    0.000    0.000    0.000    0.000 {built-in method builtins.len}
       42    0.000    0.000    0.000    0.000 _parser.py:254(get)
        1    0.000    0.000    0.001    0.001 __init__.py:272(_compile)
        1    0.000    0.000   60.118   60.118 strnaming.py:80(run_refseq_cache)
        1    0.000    0.000   60.117   60.117 refseq_cache.py:185(get_refseq)
        1    0.000    0.000    0.000    0.000 _compiler.py:509(_compile_info)
        2    0.000    0.000    0.000    0.000 pathlib.py:56(parse_parts)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.print}
        1    0.000    0.000    0.000    0.000 _parser.py:972(parse)
       39    0.000    0.000    0.000    0.000 _parser.py:249(match)
       73    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
        8    0.000    0.000    0.000    0.000 _compiler.py:214(_compile_charset)
        2    0.000    0.000    0.000    0.000 pathlib.py:484(_parse_args)
        2    0.000    0.000    0.000    0.000 gzip.py:25(open)
        1    0.000    0.000    0.001    0.001 _compiler.py:738(compile)
        2    0.000    0.000    0.000    0.000 {method 'format' of 'str' objects}
        2    0.000    0.000    0.000    0.000 pathlib.py:530(_make_child)
       18    0.000    0.000    0.000    0.000 _parser.py:286(tell)
        3    0.000    0.000    0.000    0.000 _parser.py:94(closegroup)
       28    0.000    0.000    0.000    0.000 {method 'find' of 'bytearray' objects}
        2    0.000    0.000    0.000    0.000 enum.py:686(__call__)
       18    0.000    0.000    0.000    0.000 _parser.py:172(append)
       20    0.000    0.000    0.000    0.000 _parser.py:160(__len__)
        1    0.000    0.000    0.001    0.001 __init__.py:163(match)
        4    0.000    0.000    0.000    0.000 _parser.py:369(_escape)
        4    0.000    0.000    0.000    0.000 pathlib.py:523(_format_parsed_parts)
       25    0.000    0.000    0.000    0.000 {built-in method builtins.min}
        2    0.000    0.000    0.000    0.000 enum.py:1516(__and__)
        1    0.000    0.000    0.000    0.000 pathlib.py:1111(mkdir)
        6    0.000    0.000    0.000    0.000 _parser.py:446(_uniq)
        2    0.000    0.000    0.000    0.000 cp1252.py:18(encode)
        1    0.000    0.000    0.000    0.000 _compiler.py:384(_mk_bitmap)
        3    0.000    0.000    0.000    0.000 _parser.py:82(opengroup)
       11    0.000    0.000    0.000    0.000 _parser.py:109(__init__)
        1    0.000    0.000    0.000    0.000 _parser.py:224(__init__)
        1    0.000    0.000    0.000    0.000 _compiler.py:386(<listcomp>)
        1    0.000    0.000   60.118   60.118 <string>:1(<module>)
        2    0.000    0.000    0.000    0.000 pathlib.py:515(_from_parsed_parts)
        2    0.000    0.000    0.000    0.000 gzip.py:134(__init__)
        1    0.000    0.000    0.000    0.000 pathlib.py:1008(stat)
        1    0.000    0.000    0.000    0.000 pathlib.py:1245(is_dir)
        8    0.000    0.000    0.000    0.000 _parser.py:79(groups)
        1    0.000    0.000   60.117   60.117 refseq_cache.py:81(__enter__)
        6    0.000    0.000    0.000    0.000 {built-in method fromkeys}
        3    0.000    0.000    0.000    0.000 _compiler.py:396(_simple)
        2    0.000    0.000    0.000    0.000 pathlib.py:147(splitroot)
        2    0.000    0.000    0.000    0.000 pathlib.py:765(__truediv__)
        2    0.000    0.000    0.000    0.000 {method 'match' of 're.Pattern' objects}
       20    0.000    0.000    0.000    0.000 {built-in method builtins.ord}
        1    0.000    0.000    0.000    0.000 _compiler.py:434(_get_literal_prefix)
        1    0.000    0.000    0.000    0.000 gzip.py:323(closed)
        2    0.000    0.000    0.000    0.000 {built-in method _codecs.charmap_encode}
        4    0.000    0.000    0.000    0.000 {method 'join' of 'str' objects}
        2    0.000    0.000    0.000    0.000 enum.py:1093(__new__)
        1    0.000    0.000    0.000    0.000 {built-in method _sre.compile}
        1    0.000    0.000    0.000    0.000 _compiler.py:465(_get_charset_prefix)
        6    0.000    0.000    0.000    0.000 {method 'get' of 'dict' objects}
        1    0.000    0.000    0.000    0.000 _parser.py:73(__init__)
        1    0.000    0.000    0.000    0.000 _parser.py:956(fix_flags)
        3    0.000    0.000    0.000    0.000 _compiler.py:31(_combine_flags)
        4    0.000    0.000    0.000    0.000 {method 'replace' of 'str' objects}
        4    0.000    0.000    0.000    0.000 {built-in method builtins.max}
        2    0.000    0.000    0.000    0.000 _compiler.py:568(isstring)
        2    0.000    0.000    0.000    0.000 {built-in method __new__ of type object at 0x00007FF8DC518F90}
        2    0.000    0.000    0.000    0.000 pathlib.py:94(join_parsed_parts)
        4    0.000    0.000    0.000    0.000 {method 'group' of 're.Match' objects}
        2    0.000    0.000    0.000    0.000 {built-in method sys.intern}
        3    0.000    0.000    0.000    0.000 _parser.py:168(__setitem__)
        1    0.000    0.000    0.000    0.000 refseq_cache.py:79(__init__)
        2    0.000    0.000    0.000    0.000 _compiler.py:426(_get_iscased)
        1    0.000    0.000    0.000    0.000 {method 'translate' of 'bytearray' objects}
        2    0.000    0.000    0.000    0.000 {built-in method nt.fspath}
        2    0.000    0.000    0.000    0.000 {method 'extend' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {built-in method _stat.S_ISDIR}
        2    0.000    0.000    0.000    0.000 {method 'reverse' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'items' of 'dict' objects}

**Comment by Jerrythafast** [comment]
Hi @waweey,

Strangely, it appears that STRNaming hasn't cleant up its lock file during an earlier attempt. Could you try again after manually deleting this file? `C:\Users\q8dj\.strnaming-cache\cache.lock`

Jerry

**Comment by Jerrythafast** [comment]
Fixed in v2.1.0
